
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: drivers_db

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6.0
    container_name: drivers-mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"



  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=drivers_db
      - DB_PORT=5432
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=drivers_mongo
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
    depends_on:
      - db

    ports:
      - "3000:3000"

  frontend:

    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
  mongodata:
